# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-covid19-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # conda-forge packages
  - conda-forge::python=3.7.3
  - conda-forge::r-base=3.6.2
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::pigz=2.3.4

  # bioconda packages
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.8
  - bioconda::fastp=0.20.0
  - bioconda::nanoplot=1.29.0
  - bioconda::bwa=0.7.17
  - bioconda::minimap2=2.17
  - bioconda::samtools=1.9
  - bioconda::bedtools=2.29.2
  - bioconda::picard=2.22.0
  - bioconda::kraken2=2.0.8_beta
  - bioconda::bbmap=38.79
  - bioconda::spades=3.14.0
  - bioconda::unicycler=0.4.8
  - bioconda::bandage=0.8.1
  - bioconda::mafft=7.455
  - bioconda::fasttree=2.1.10
  - bioconda::lofreq=2.1.4
  - bioconda::snpeff=4.3.1t
  - bioconda::snpsift=4.3.1t
  - bioconda::porechop=0.2.3_seqan2.1.1
  - bioconda::filtlong=0.2.0
  - bioconda::emboss=6.6.0
  - bioconda::hyphy=2.5.6
  - bioconda::adam=0.31.0
  - bioconda::cytoscape=3.7.2
  - bioconda::dsh-bio=1.3.3
  - bioconda::odgi=0.2
  #- bioconda::sra-tools=2.10.3           ## Use NF native fromSRA() instead?
  #- bioconda::ncbi-acc-download=0.2.6    ## Use NF native fromSRA() instead?
